---
- hosts: masterportal
  remote_user: root
  vars:
    - igtfkey: "https://dl.igtf.net/distribution/igtf/current-new/GPG-KEY-EUGridPMA-RPM-3"
    - igtf_current_baseurl: "http://dist.eugridpma.info/distribution/igtf/current-new/"
  tasks:

# You might need to disable SELinux. The setup has not been tested with it yet. 

# The libselinux-python is still needed by asnible
  - name: install libselinux (ansible selinux dependency)
    yum:
      name: libselinux-python
      state: present
#  - selinux: state=disabled

# Install IGTF trust anchors

  - name: adding IGTF GPG key
    rpm_key:
      key: "{{ igtfkey }}"
      state: present

  - name: adding IGTF repositories (current-new)
    yumrepo:
      name: eugridpma
      description: EUGridPMA
      baseurl: "{{ igtf_current_baseurl }}"
      file: eugridpma
      gpgcheck: yes
      enabled: yes
      gpgkey: "{{ igtfkey }}"

  - name: install trust roots
    yum:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
       - ca_TERENA-eScience-SSL-CA-3.noarch
#      - ca_policy_igtf-classic
#      - ca_policy_igtf-mics
       

# Install EPEL repository

  - name: install epel
    yum:
      name: epel-release
      state: present
