---
- hosts: credstore
  remote_user: root
  vars_files:
    - credstore_env.yml
  roles:
    - credstore
  tasks:
    - name: start myproxy
      service: name=myproxy-server state=restarted enabled=yes
