---
- hosts: masterportal
  remote_user: root
  roles:
    - masterportal
  tasks:
    - name: start tomcat
      service: name=tomcat6 state=restarted enabled=yes
    - name: start httpd
      service: name=httpd state=restarted enabled=yes
