---
- hosts: masterportal
  remote_user: root
  vars_files:
    - "{{ configdir }}/basic_env.yml"
    - "{{ configdir }}/masterportal_env.yml"
    - "{{ configdir }}/secrets_env.yml"
  roles:
    - basic
    - masterportal
