---
- hosts: sshhost
  remote_user: root
  vars_files:
    - "{{ configdir }}/basic_env.yml"
    - "{{ configdir }}/sshhost_env.yml"
    - "{{ configdir }}/secrets_env.yml"
  roles:
    - basic
    - sshhost
