---
########################################################################
### OVERRIDDEN VALUES FOR THE masterportal ROLE
########################################################################

### Trust anchors: for the MasterPortal this MUST include:
### - CA for hostcert of masterportal, credstore and sshhost
### - CA for hostcert of delegation server
### Settings here override also those in common_env.yml

### trust anchor as RPM
#trust_anchor_packages:
#  - "ca_TERENA-eScience-SSL-CA-3"

### trust anchor as tarball
#trust_anchor_tarballs:
#  - "internalca.tar.gz"

### When the hostcert is signed by an intermediate CA,
### specify the pem file here:
hostcert_intermediate: /etc/grid-security/certificates/TERENA-eScience-SSL-CA-3.pem


### Whether to enable the autoregistration endpoint
### WARNING: should only be used if the request is already verified
### previously, e.g. via a proxy and OIDC federation
#use_autoregister: true

### Override mp_server_sshkey_scope: set to empty or nothing to disable the
### requiring of a special scope for accessing the sshkeys API endpoint.
#mp_server_sshkey_scope: ""

### Configure the mp_client_conf_lifetime to set the lifetime sent with every
### /getcert request to the delegation server. This will determine the lifetime
### of the EEC returned by the Online CA, as well as the lifetime of the created
### Long Lived Proxy Certificate.
mp_client_conf_lifetime: 950400


### Default JSON web key id:
mp_server_jwk_key_id: ""


### Fill in the credstore DN. This is going to be the expected DN of the
### myproxy-server. Leave undefined to do normal host verification.
credstore_dn: "/C=NL/O=Example/OU=Org/CN=credstore"


### Fill in the delegation server oauth2 endpoint that will be used by this
### Master Portal
deleg_server_auth: https://delegation-server/oauth2
