---
########################################################################
### OVERRIDDEN VALUES FOR THE masterportal ROLE
########################################################################

### Trust anchors: for the MasterPortal this MUST include:
### - CA for hostcert of masterportal, credstore and sshhost
### - CA for hostcert of delegation server
### Settings here override also those in common_env.yml

### trust anchor as RPM
#trust_anchor_packages:
#  - "ca_TERENA-eScience-SSL-CA-3"

### trust anchor as tarball
#trust_anchor_tarballs:
#  - "internalca.tar.gz"

### When the hostcert is signed by an intermediate CA,
### specify the pem file here:
#hostcert_intermediate: /etc/grid-security/certificates/TERENA-eScience-SSL-CA-3.pem
hostcert_intermediate: /etc/grid-security/certificates/GEANTeScienceSSLCA4.pem


### Whether to enable the autoregistration endpoint
### WARNING: should only be used if the request is already verified
### previously, e.g. via a proxy and OIDC federation
#use_autoregister: true

### Override mp_server_sshkey_scope: set to empty or nothing to disable the
### requiring of a special scope for accessing the sshkeys API endpoint.
#mp_server_sshkey_scope: ""

### Override the mp_client_conf_lifetime to set the lifetime sent with every
### /getcert request to the delegation server. This will determine the lifetime
### of the EEC returned by the Online CA, as well as the lifetime of the created
### Long Lived Proxy Certificate.
#mp_client_conf_lifetime: "{{ eec_lifetime }}"

### Override the mp_server_conf_lifetime which is used in combination
### with mp_server_conf_tolerance to set the maximum lifetime for retrieved
### proxies from the MasterPortal. mp_server_conf_lifetime typically should
### match max_proxy_lifetime in the myproxy-server.config file (but there in
### hours).
#mp_server_conf_lifetime: "{{ max_proxy_lifetime }}"

### Override the mp_server_conf_tolerance, see mp_server_conf_lifetime. This
### effectively sets a limit to the frequency with which an EEC can be retrieved
### from the CA.
#mp_server_conf_tolerance: 86400

### Override default lifetime of returned short-lived proxies in seconds
#mp_server_conf_def_proxy_lifetime: 43200


### Override name of the input file for the MasterPortal JSON web key
#mp_server_jwk_input_file: mp_example.jwk
### Default MasterPortal JSON web key id:
mp_server_jwk_key_id: "1234567890ABCDEF1234567890ABCDEF"


### Fill in the credstore DN. This is going to be the expected DN of the
### myproxy-server. Leave undefined to do normal host verification.
credstore_dn: "/C=NL/O=Example/OU=Org/CN=credstore"


### Fill in the delegation server oauth2 endpoint that will be used by this
### Master Portal
deleg_server_auth: https://delegation-server/oauth2
