---

### java constants

javax_mail_url: "https://github.com/javaee/javamail/releases/download/JAVAMAIL-1_6_1/javax.mail.jar"
java_home: /usr/java/default

### tomcat constants

tomcat_packages:
 - tomcat6
 - tomcat6-admin-webapps

catalina_home: /usr/share/tomcat6
tomcat_user: tomcat
tomcat_service: tomcat6

### apache

httpd_packages:
  - httpd
  - httpd-tools
  - mod_ssl

httpd_service: httpd

### mysql

mysql_service: mysqld

# Note: we use the shipped mysql-connector-java, not the system one.
# Also note that the code determines whether we can use
# mysql-connector-java-5.1.X or mysql-connector-java-8.0.X since they have a
# different class name for the driver. In either case, we ship along the
# connector with the war file, so no need for the system version.
# Note that 5.1.X is required for CentOS6.

mysql_packages:
  - mysql
  - mysql-server
  - MySQL-python
