---

# java constants

javax_mail_url: "https://github.com/javaee/javamail/releases/download/JAVAMAIL-1_6_1/javax.mail.jar"
java_home: /usr/java/default

# tomcat constants

tomcat_packages:
 - tomcat6
 - tomcat6-admin-webapps

catalina_home: /usr/share/tomcat6
tomcat_user: tomcat
tomcat_service: tomcat6

# apache

httpd_packages:
  - httpd
  - httpd-tools
  - mod_ssl

httpd_service: httpd

# mysql

mysql_packages:
  - mysql
  - mysql-server
  - MySQL-python
  - mysql-connector-java

mysql_connector_path: /usr/share/java
mysql_connector: mysql-connector-java.jar
