---

### enabled and disabled services

enabled_services:
 - tomcat
 - httpd
 - mariadb

### java constants

javax_mail_url: "https://github.com/javaee/javamail/releases/download/JAVAMAIL-1_6_1/javax.mail.jar"
java_home: /usr/java/default

### tomcat constants

tomcat_packages:
 - tomcat
 - tomcat-admin-webapps

catalina_home: /usr/share/tomcat
tomcat_user: tomcat
tomcat_service: tomcat

### apache

httpd_packages:
  - httpd
  - httpd-tools
  - mod_ssl

httpd_service: httpd

### mysql

### NOTE
### THERE IS NO MYSQL PACKAGE IN CENTOS7 SINCE IT COMES WITH THE MARIADB IMPLEMENTATION
### YOU CAN INSTALL MTSQL FROM THE REPOSITORY BELOW, BUT THIS WILL NOT WORK PROPERLY

#mysql_repo_baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
#mysql_repo_connectors_baseurl: http://repo.mysql.com/yum/mysql-connectors-community/el/7/$basearch/
#mysql_repo_gpgkey: https://repo.mysql.com/RPM-GPG-KEY-mysql

#mysql_service: mysqld

#mysql_packages:
#  - mysql-community-server
#  - mysql-connector-java
#  - mysql-connector-python


### mariadb

# NOTE
# THE MARIADB PACKAGES ARE IN THE CENTOS7 REPOS, BUT THERE IS NO MARIADB JDBC CONNECTOR PROVIDED
# THE CONNECTOR DOWLOADED FROM THE OFFICIAL MARIADB WEBPAGE DOES NOT WORK PROPERLY ON CENTOS7
# THEREFOR WE USE THE CONNECTOR PROVIDED BY MYSQL INSTEAD.

# THE ABOVE EFFECTIVELY MEANS THAT OA4MP WILL RUN WITH 'MYSQL' CONNECTOR AND IMPLEMENTATION
# BUT THE UNDERLYING DATABASE WILL ACTUALLY BY MARIADB.

mysql_service: mariadb

mysql_packages:
  - mariadb
  - mariadb-server
  - mysql-connector-java
  - MySQL-python

mysql_connector_path: /usr/share/java
mysql_connector: mysql-connector-java.jar

### postgresql

postgresql_packages:
  - postgresql
  - postgresql-server
  - postgresql-jdbc
  - python-psycopg2

postgresql_connector_path: /usr/share/java
postgresql_connector: postgresql-jdbc.jar
