---

### enabled and disabled services

enabled_services:
 - tomcat
 - httpd
 - mariadb

### java constants

javax_mail_url: "https://github.com/javaee/javamail/releases/download/JAVAMAIL-1_6_1/javax.mail.jar"
java_package: java-1.8.0-openjdk-headless
java_home: /usr/lib/jvm/jre-1.8.0

### tomcat constants

tomcat_packages:
 - tomcat
 - tomcat-admin-webapps

catalina_home: /usr/share/tomcat
tomcat_user: tomcat
tomcat_service: tomcat

### apache

httpd_packages:
  - httpd
  - httpd-tools
  - mod_ssl

httpd_service: httpd

### mysql

### NOTE
### THERE IS NO MYSQL PACKAGE IN CENTOS7 SINCE IT COMES WITH THE MARIADB IMPLEMENTATION
### YOU CAN INSTALL MTSQL FROM THE REPOSITORY BELOW, BUT THIS WILL NOT WORK PROPERLY

#mysql_repo_baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
#mysql_repo_connectors_baseurl: http://repo.mysql.com/yum/mysql-connectors-community/el/7/$basearch/
#mysql_repo_gpgkey: https://repo.mysql.com/RPM-GPG-KEY-mysql

#mysql_service: mysqld

#mysql_packages:
#  - mysql-community-server
#  - mysql-connector-java
#  - mysql-connector-python


### mariadb

# NOTE
# THE MARIADB PACKAGES ARE IN THE CENTOS7 REPOS, BUT THERE IS NO MARIADB JDBC CONNECTOR PROVIDED
# THE CONNECTOR DOWLOADED FROM THE OFFICIAL MARIADB WEBPAGE DOES NOT WORK PROPERLY ON CENTOS7
# THEREFOR WE USE THE CONNECTOR PROVIDED BY MYSQL INSTEAD.

# THE ABOVE EFFECTIVELY MEANS THAT OA4MP WILL RUN WITH 'MYSQL' CONNECTOR AND IMPLEMENTATION
# BUT THE UNDERLYING DATABASE WILL ACTUALLY BY MARIADB.

# Note: we use the shipped mysql-connector-java, not the system one.
# Also note that the code determines whether we can use
# mysql-connector-java-5.1.X or mysql-connector-java-8.0.X since they have a
# different class name for the driver. In either case, we ship along the
# connector with the war file, so no need for the system version.
# Note that 5.1.X is required for CentOS6, while 8.0.X can be used for CentOS7.

mysql_service: mariadb

mysql_packages:
  - mariadb
  - mariadb-server
  - MySQL-python

### postgresql

postgresql_packages:
  - postgresql
  - postgresql-server
  - postgresql-jdbc
  - python-psycopg2

postgresql_connector_path: /usr/share/java
postgresql_connector: postgresql-jdbc.jar
