---
# Create the proxy user
- import_tasks: proxyuser.yml

# Setup the client credentials
- import_tasks: proxycreds.yml

# add the myproxy and authz scripts
- import_tasks: scripts.yml

# Update the sshd config
- import_tasks: sshd.yml

# Update the access.conf file for the proxy user
- import_tasks: accessconf.yml
