---
# Create the proxy user
- include_tasks: proxyuser.yml

# Setup the client credentials
- include_tasks: proxycreds.yml

# add the myproxy and authz scripts
- include_tasks: scripts.yml

# this is strictly speaking only needed if the SSH runs on a separate host from
# the Master Portal, otherwise it will be covered by the MasterPortal's
# iptables task
- include_tasks: iptables.yml

# Update the sshd config
- include_tasks: sshd.yml

# Update the access.conf file for the proxy user
- include_tasks: accessconf.yml
