---
### general packages that should be present

general_packages: 
  - libselinux-python
  - net-tools
  - bind-utils
  - postfix
  - mailx
  - sysstat
  - ntp
  - iptables-services
  - nscd
  - fetch-crl

### list of enabled and disabled services 

enabled_services:
  - ntpd
  - nscd
  - fetch-crl-cron
  - iptables
  - ip6tables

disabled_services:
  - NetworkManager
  - wpa_supplicant
  - firewalld

### additional repository information

igtfkey: "https://dl.igtf.net/distribution/igtf/current-new/GPG-KEY-EUGridPMA-RPM-3"
igtf_current_baseurl: "http://dist.eugridpma.info/distribution/igtf/current-new/"

epelrpm: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
epelkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"

OS: "RH7"
