---

# include tasks to execute

- include_tasks: selinux.yml
- include_tasks: sshd.yml
- include_tasks: repos.yml
- include_tasks: general.yml
- include_tasks: network.yml
- include_tasks: hostcreds.yml
- include_tasks: access.yml
- include_tasks: iptables.yml

# list of disabled services

- name: disable services
  service: name={{ item }} state=stopped enabled=no
  with_items: "{{ disabled_services }}" 

# list of enabled services

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
