---

# include tasks to execute

- import_tasks: hostname.yml
- import_tasks: selinux.yml
- import_tasks: sshd.yml

- import_tasks: repos.yml
- import_tasks: yum.yml

- import_tasks: network.yml
- import_tasks: iptables.yml
- import_tasks: access.yml
- import_tasks: ntpd.yml

- import_tasks: fetchcrl.yml
- import_tasks: hostcreds.yml

- import_tasks: postfix.yml

- import_tasks: vomses.yml

# list of disabled services
# need to stop e.g. firewalld before starting iptables

- name: disable services
  service: name={{ item }} state=stopped enabled=no
  ignore_errors: True
  with_items: "{{ disabled_services }}"

# list of enabled services

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
