---

# include tasks to execute

- include_tasks: hostname.yml
- include_tasks: selinux.yml
- include_tasks: sshd.yml

- include_tasks: repos.yml
- include_tasks: yum.yml

- include_tasks: network.yml
- include_tasks: iptables.yml
- include_tasks: access.yml
- include_tasks: ntpd.yml

- include_tasks: fetchcrl.yml
- include_tasks: hostcreds.yml

# list of disabled services
# need to stop e.g. firewalld before starting iptables

- name: disable services
  service: name={{ item }} state=stopped enabled=no
  with_items: "{{ disabled_services }}"

# list of enabled services

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
