---

# Change selinux settings

# You might need to disable SELinux. The setup has not been tested with it yet.
# Disable SELinux (Shibboleth SP requirement)
#- name: disable selinux 
#  selinux: state=disabled

- name: put selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
