---

# installing vomses when present
- name: check vomses
  local_action:
    module: stat
    path: "roles/basic/files/{{ vomses_input }}"
  register: vomses

- name: copy vomses as directory
  copy:
    src: "{{ vomses_input }}/"
    dest: "{{ vomses_location }}"
    mode: 0644
  when: vomses.stat.exists and vomses.stat.isdir

- name: copy vomses as file
  copy:
    src: "{{ vomses_input }}"
    dest: "{{ vomses_location }}"
    mode: 0644
  when: vomses.stat.exists and vomses.stat.isdir == False
