---
########################################################################
### DEFAULT VALUES FOR THE masterportal ROLE
########################################################################

### certificates

### define following when the hostcert is signed by an intermediate CA
#hostcert_intermediate: "{{ x509_cert_dir }}/GEANTeScienceSSLCA4.pem"
#hostcert_intermediate: "{{ x509_cert_dir }}/TERENA-eScience-SSL-CA-3.pem"


### Keyutil jar file
keyutil_jar: keyutil-0.4.0.jar


### OA4MP Client

mp_client_db: oa2client
mp_client_db_user: oa4mp-client

mp_client_dir: /var/www/client
mp_client_conf_dir: "{{ mp_client_dir }}/conf"
mp_client_conf_file: "{{ mp_client_conf_dir }}/cfg.xml"
mp_client_truststore: "{{ mp_client_conf_dir }}/trust-store.jks"
mp_client_keystore: "/etc/grid-security/hostcred.p12"
mp_client_conf: mysql
#mp_client_conf: fileStore
mp_client_log_dir: "{{ mp_client_dir }}/log"
mp_client_log_size: 1000000
mp_client_log_debug: "info"
mp_client_storage_dir: "{{ mp_client_dir }}/storage"
### requested lifetime for the long-lived proxies stored in the MasterPortal
mp_client_conf_lifetime: "{{ eec_lifetime }}"


### OA4MP Server

mp_server_db: oa2server
mp_server_db_user: oa4mp-server

mp_server_dir: /var/www/server
mp_server_conf_dir: "{{ mp_server_dir }}/conf"
mp_server_conf_file: "{{ mp_server_conf_dir }}/cfg.xml"
#mp_server_truststore: "{{ mp_server_conf_dir }}/trust-store.jks"
mp_server_keystore: "/etc/grid-security/hostcred.p12"
mp_server_conf: mysql
#mp_server_conf: fileStore
mp_server_log_dir: "{{ mp_server_dir }}/log"
mp_server_log_size: 1000000
mp_server_log_debug: "info"
mp_server_storage_dir: "{{ mp_server_dir }}/storage"
mp_server_tools_dir: "{{ mp_server_dir }}/tools"
### (mp_server_conf_lifetime -  mp_server_conf_tolerance) is the maximum
### requestable lifetime in seconds for short-lived proxies returned by the
### MasterPortal. mp_server_conf_lifetime typically matches the
### max_proxy_lifetime defined in the myproxy-server.config (there in hours)
### while the mp_server_conf_tolerance ensures we cannot overload the CA since
### the MasterPortal will request new EECs not more often than once every
### tolerance seconds.
mp_server_conf_lifetime: "{{ max_proxy_lifetime }}"
mp_server_conf_tolerance: 86400
### default lifetime of returned short-lived proxies in seconds
mp_server_conf_def_proxy_lifetime: 43200
### max number of ssh keys per person
mp_server_max_sshkeys: 5
### scope required for accessing the ssh keys API
mp_server_sshkey_scope: "eu.rcauth.sshkeys"
### disabled/enabled scopes for the server
mp_server_disabled_scopes: []
mp_server_enabled_scopes:
- org.cilogon.userinfo
### scopes local to the server (not forwarded to the DS)
mp_server_local_scopes:
- "{{ mp_server_sshkey_scope }}"

### Whether we use refreshtokens
mp_server_refreshtokens: "true"

### Masterportal signing keys
### src filename
mp_server_jwk_input_file: mp.jwk
### dest filename
mp_server_jwk_file: "{{ mp_server_conf_dir }}/mp.jwk"



### Email settings for notifications about new client approval requests.
### See http://grid.ncsa.illinois.edu/myproxy/oauth/server/configuration/server-email.xhtml
mail_server: "localhost"
mail_recipients: "root@localhost"
mail_enabled: "true"
mail_use_SSL: "false"
mail_debug: "true"
mail_message_template: "{{ mp_server_conf_dir }}/mail_message.template"
mail_subject_template: "{{ mp_server_conf_dir }}/mail_subject.template"

### VO Portal

### When vo_portal is undefined, the VO portal will not be deployed or
### configured
vo_portal: vo-portal
vo_portal_dir: /var/www/voportal
vo_portal_conf_dir: "{{ vo_portal_dir }}/conf"
vo_portal_conf_file: "{{ vo_portal_conf_dir }}/cfg.xml"
vo_portal_truststore: "{{ vo_portal_conf_dir }}/trust-store.jks"
vo_portal_conf: vo-portal-config
vo_portal_log_dir: "{{ vo_portal_dir }}/log"
vo_portal_log_size: 1000000
vo_portal_log_debug: "info"
vo_portal_storage_dir: "{{ vo_portal_dir }}/storage"
vo_portal_conf_lifetime: 86400
### disabled/enabled scopes for the vo-portal
vo_portal_disabled_scopes: []
vo_portal_enabled_scopes:
- org.cilogon.userinfo

### SSH Key portal

### When sshkey_portal is undefined, the sshkey portal will not be deployed or
### configured
sshkey_portal: sshkeys
sshkey_portal_dir: /var/www/sshkeyportal
sshkey_portal_conf_dir: "{{ sshkey_portal_dir }}/conf"
sshkey_portal_conf_file: "{{ sshkey_portal_conf_dir }}/cfg.xml"
sshkey_portal_truststore: "{{ sshkey_portal_conf_dir }}/trust-store.jks"
sshkey_portal_conf: sshkey-portal-config
sshkey_portal_log_dir: "{{ sshkey_portal_dir }}/log"
sshkey_portal_log_size: 1000000
sshkey_portal_log_debug: "info"
sshkey_portal_storage_dir: "{{ sshkey_portal_dir }}/storage"
### disabled/enabled scopes for the sshkey-portal
sshkey_portal_disabled_scopes:
- edu.uiuc.ncsa.myproxy.getcert
- email
sshkey_portal_enabled_scopes:
- org.cilogon.userinfo
- "{{ mp_server_sshkey_scope }}"
### configuration for displaying the name and IdP
sshkey_name_claim: name
sshkey_given_name_claim: given_name
sshkey_family_name_claim: family_name
sshkey_idp_display_name_claim: idp_display_name
