---

# Install apache

- name: install httpd
  yum: name={{item}} state=present
  with_items: "{{ httpd_packages }}"

# configure

- name: httpd config file present
  template:
    src: ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart httpd

- name: httpoxy config present
  template:
    src: 00-httpoxy.conf.j2
    dest: /etc/httpd/conf.d/00-httpoxy.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart httpd

# replace welcome page

- name: replace apache welcome page
  stat:
    path: /var/www/html/index.html
  ignore_errors: yes
  register: index_page

- name: create index page
  file:
    path: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
    state: touch
  when: index_page.stat.exists == false
