---

# java tasks

- name: install java
  yum:
    name: "{{ java_package }}"
    state: present

- name: JAVA_HOME present in bashrc
  lineinfile:
    dest: /etc/bashrc
    state: present
    line: "export JAVA_HOME={{ java_home }}"
    regexp: "^export JAVA_HOME=.*"
    insertafter: EOF
    backup: yes
