---

### services required for masterportal

- import_tasks: java.yml
- import_tasks: tomcat.yml
- import_tasks: httpd.yml
- import_tasks: mariadb.yml
#- import_tasks: mysql.yml

# Make sure the keyutil jar file is remotely available
- import_tasks: keyutil.yml

# Include tasks to deploy master portal

- import_tasks: oa4mp-client.yml
- import_tasks: oa4mp-server.yml

### Setup the self-service SSH public key upload portal. This can be used in
### combination with the SSH host (see the sshhost playbook) to download proxy
### certificates using SSH and a public key.

- import_tasks: sshkey-portal.yml
  when: sshkey_portal is defined

### The VO Portal is not part of the Master Portal, it's only a simple
### Master Portal client installed alongside it for testing purposes.

- import_tasks: vo-portal.yml
  when: vo_portal is defined

### enable services

- name: enable and start services
  service: name={{ item }} state=restarted enabled=yes
  with_items: "{{ enabled_services }}"
