---

# Include dependencies

- include_tasks: dep-java.yml
- include_tasks: dep-tomcat.yml
- include_tasks: dep-httpd.yml

# Currently the Master Portal does not support database backend
# This will be fixed in to future, but for now, filesystem backend
# is used.

#- include_tasks: dep-mysql.yml
- include_tasks: dep-mariadb.yml

# Make sure the keyutil jar file is remotely available
- include_tasks: dep-keyutil.yml

# Include tasks to deploy master portal

- include_tasks: oa4mp-client.yml
- include_tasks: oa4mp-server.yml

# Setup the self-service SSH public key upload portal. This can be used in
# combination with the SSH host (see the sshhost playbook) to download proxy
# certificates using SSH and a public key.

- include_tasks: sshkey-portal.yml
  when: sshkey_portal is defined

# The VO Portal is not part of the Master Portal, it's only a simple 
# Master Portal client installed alongside it for testing purposes.

- include_tasks: vo-portal.yml
  when: vo_portal is defined

- include_tasks: iptables.yml

# list of enabled services

- name: start tomcat
  service: name={{ tomcat_service }} state=restarted enabled=yes
- name: start httpd
  service: name={{ httpd_service }} state=restarted enabled=yes
