---

# Install MySQL Server

- name: install MySQL
  yum:
    name: "{{ mysql_packages }}"
    state: present
  register: mysql_installation

- name: make a link to the connector
  file:
    src: "{{ mysql_connector_path }}/{{ mysql_connector }}"
    dest: "{{ catalina_home }}/lib/{{ mysql_connector }}"
    owner: root
    group: root
    state: link

# Start MySQL Server

- name: start the MySQL service
  service: name=mysqld state=started enabled=yes

# Configure root password (but only on fresh mysql installations)

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - localhost
  when: mysql_installation.changed

# check MP Server DB
# NOTE: we cannot just check the DB without creating, but to prevent import from
# running every time we have to run 'present', hence we cannot postpone creating
# the database until we run import. Creating the DB in the script is therefore
# not actually needed nor done.

- name: create MP Server DB
  mysql_db:
    name: "{{ mp_server_db }}"
    state: present
    encoding: utf8
    login_user: root
    login_password: "{{ mysql_root_password }}"
  register: server_db
  when: mysql_root_password is defined

- name: update mysql MP Server user account
  mysql_user:
    name: "{{ mp_server_db_user }}"
    host: "{{ item }}"
    password: "{{ mp_server_db_pw }}"
    priv: "{{ mp_server_db }}.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items:
    - 127.0.0.1
    - localhost
  when: mysql_root_password is defined

- name: copy MP Server sql script
  template:
    src: mp-oa2-server-mysql.sql.j2
    dest: /tmp/mp-oa2-server-mysql.sql
  when: server_db is defined and server_db.changed

- name: execute MP Server sql script
  mysql_db:
    state: import
    name: all
    target: /tmp/mp-oa2-server-mysql.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: server_db is defined and server_db.changed

- name: remove MP Server sql script
  file:
    path: /tmp/oa4mp-server-mysql.sql
    state: absent
  when: server_db is defined and server_db.changed

# check MP Client DB
# NOTE: we cannot just check the DB without creating, but to prevent import from
# running every time we have to run 'present', hence we cannot postpone creating
# the database until we run import. Creating the DB in the script is therefore
# not actually needed nor done.

- name: create MP Client DB
  mysql_db:
    name: "{{ mp_client_db }}"
    state: present
    encoding: utf8
    login_user: root
    login_password: "{{ mysql_root_password }}"
  register: client_db
  when: mysql_root_password is defined

- name: update mysql MP Client user account
  mysql_user:
    name: "{{ mp_client_db_user }}"
    host: "{{ item }}"
    password: "{{ mp_client_db_pw }}"
    priv: "{{ mp_client_db }}.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items:
    - 127.0.0.1
    - localhost
  when: mysql_root_password is defined

- name: copy MP Client sql script
  template:
    src: mp-oa2-client-mysql.sql.j2
    dest: /tmp/mp-oa2-client-mysql.sql
  when: client_db is defined and client_db.changed

- name: execute MP Client sql script
  mysql_db:
    state: import
    name: all
    target: /tmp/mp-oa2-client-mysql.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: client_db is defined and client_db.changed

- name: remove MP Client sql script
  file:
    path: /tmp/mp-oa2-client-mysql.sql
    state: absent
  when: client_db is defined and client_db.changed
