---

# make sure directory structure is in place

- name: client directory exists
  file: 
    path: "{{ mp_client_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"

- name: client conf dir exists
  file: 
    path: "{{ mp_client_conf_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"


- name: client log exists
  file: 
    path: "{{ mp_client_log_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"

- name: client storage exists
  file:
    path: "{{ mp_client_storage_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"

# place configuration

- name: client config file
  template:
    src: client-cfg.xml.j2
    dest: "{{ mp_client_conf_file }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0600
    backup: yes

# (no need for a trust store as long as trusted certs are in /etc/grid-security/certificates)
# place trust and key stores

- name: add trusted CAs to client trust store
  raw: "java -jar {{ keyutil_jar }} -i -F -n {{ mp_client_truststore }} -p {{ mp_client_truststore_pw }} -e {{ certificates }}/*.pem"

- name: add the right permission to the trust store
  file:
    path: "{{ mp_client_truststore }}"
    owner: tomcat
    group: tomcat
    mode: 0644

# convert hostcert into pkcs12, so that oa4mp can load it in its keystore

- name: add hostcert to keystore
  command: "openssl pkcs12 -export -in {{ hostcert }} -inkey {{ hostkey }} -out {{ mp_client_keystore }} -name hostcred -CApath {{ certificates }} -chain -passout pass:{{ mp_client_keystore_pw }}"

- name: add the right permission to the key store
  file: 
    path: "{{ mp_client_keystore }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0400

# deploy war file

- name: stop tomcat for the war switch
  service:
    name: "{{ tomcat_service }}"
    state: stopped

- name: delete old deployment
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{ catalina_home }}/webapps/{{ mp_client }}"
    - "{{ catalina_home }}/webapps/{{ mp_client }}.war"

- name: copy war 
  copy:
    src: mp-oa2-client.war
    dest: "{{ catalina_home }}/webapps/{{ mp_client}}.war"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0644
  notify: restart tomcat

