---

# make sure directory structure is in place

- name: server directory exists
  file: 
    path: "{{ mp_server_dir }}"
    state: directory
    owner: tomcat
    group: tomcat

- name: server conf dir exists
  file: 
    path: "{{ mp_server_conf_dir }}"
    state: directory
    owner: tomcat
    group: tomcat


- name: server log exists
  file: 
    path: "{{ mp_server_log_dir }}"
    state: directory
    owner: tomcat
    group: tomcat

- name: server storage exists
  file:
    path: "{{ mp_server_storage_dir }}"
    state: directory
    owner: tomcat
    group: tomcat

# place configuration

- name: server config file
  template:
    src: server-cfg.xml.j2
    dest: "{{ mp_server_conf_file }}"
    owner: tomcat
    group: tomcat
    mode: 0600
    backup: yes

# place trust and key stores

- name: retrieve all trusted CAs
  command: "find {{ certificates }} -type f -name '*.pem'"
  register: trusted_cas

- name: add trusted CAs to client trust store
  raw: /usr/bin/keytool -list -keystore "{{ mp_server_truststore }}" -storepass "{{ mp_server_truststore_pw }}" -alias `basename "{{ item }}"` || /usr/bin/keytool -importcert -noprompt -trustcacerts -keystore "{{ mp_server_truststore }}" -storepass "{{ mp_server_truststore_pw }}" -alias `basename "{{ item }}"`  -file "{{ item }}"
  with_items: trusted_cas.stdout_lines

- name: add the right permission to the trust store
  file:
    path: "{{ mp_server_truststore }}"
    owner: tomcat
    group: tomcat
    mode: 0644

- name: add hostcert to keystore
  command: openssl pkcs12 -export -in "{{ hostcert }}" -inkey "{{ hostkey }}" -out "{{ mp_server_keystore }}" -name hostcred -CApath "{{ certificates }}" -chain -passout "pass:{{ mp_server_keystore_pw }}"

- name: add the right permission to the key store
  file:
    path: "{{ mp_server_keystore }}"
    owner: tomcat
    group: tomcat
    mode: 0400

# deploy war file

- name: delete old deployment
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{ catalina_home }}/webapps/{{ mp_server }}"
    - "{{ catalina_home }}/webapps/{{ mp_server }}.war"

- name: copy war 
  copy:
    src: mp-oa2-server.war
    dest: "{{ catalina_home }}/webapps/{{ mp_server }}.war"
    owner: tomcat
    group: tomcat
    mode: 0644
