---

# make sure directory structure is in place

- name: voportal directory exists
  file: 
    path: "{{ vo_portal_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"

- name: voportal conf dir exists
  file: 
    path: "{{ vo_portal_conf_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"


- name: voportal log exists
  file: 
    path: "{{ vo_portal_log_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"

- name: voportal storage exists
  file: 
    path: "{{ vo_portal_storage_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"

# place configuration

- name: voportal config file
  template:
    src: vo-portal-cfg.xml.j2
    dest: "{{ vo_portal_conf_file }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0600
    backup: yes

# (no need for a trust store as long as trusted certs are in x509_cert_dir)
# place trust and key stores

- name: add trusted CAs to client trust store
  raw: "java -jar {{ keyutil_jar }} -i -F -n {{ vo_portal_truststore }} -p {{ vo_portal_truststore_pw }} -e {{ x509_cert_dir }}/*.pem"

- name: add the right permission to the trust store
  file:
    path: "{{ vo_portal_truststore }}"
    owner: tomcat
    group: tomcat
    mode: 0644

# deploy war file

- name: stop tomcat for the war switch
  service:
    name: "{{ tomcat_service }}"
    state: stopped

- name: delete old deployment
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{ catalina_home }}/webapps/{{ vo_portal }}"
    - "{{ catalina_home }}/webapps/{{ vo_portal }}.war"

- name: copy war 
  copy:
    src: vo-portal.war
    dest: "{{ catalina_home }}/webapps/{{ vo_portal }}.war"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0644
  notify: restart tomcat

