---
- include: myproxy-credstore.yml

# The CA certificate bundle from the appropriate Delegation Server has to be copied to the 
# Credential Store, so that incoming certificates can be verified for storage

- include: deploy-trustedca.yml

# this is only needed if the Credential Store runs on a separate host from the
# Master Portal, otherwise we are allowed via the related/established rule
- include: iptables.yml

- name: start myproxy
  service: name=myproxy-server state=restarted enabled=yes
