---
- import_tasks: myproxy-credstore.yml

# Need the IGTF distribution to be able to talk to VOMS servers
- import_tasks: deploy-igtf-distrib.yml

# add the purging script to clean up expired/revoked certificates
- import_tasks: purger.yml

- name: start myproxy
  service: name=myproxy-server state=restarted enabled=yes
